steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/compound/api:latest',
    '-f', 'backend/Dockerfile',
    '.'
  ]
images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/compound/api:latest'
